version: '3'
services:
  frontend:
    container_name: codEdit2r
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USERPOLLING=true